[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/backend/*"
  to = "https://orkyst.com/backend/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*", Access-Control-Allow-Credentials = "true" }

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store"